services:
  php:
    container_name: rechi-travel-orders-api_php
    build:
      args:
        user: rechi
        uid: 1000
      context: ./
      dockerfile: docker/Dockerfile
    image: landing-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  nginx:
    container_name: rechi-travel-orders-api_nginx
    hostname: rechi-travel-orders-api.localhost
    image: nginx:alpine
    restart: always
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/logs/:/var/log/nginx/
    ports:
        - 80:80
    environment:
        - NGINX_PORT=80

  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql.localhost
    restart: always
    volumes:
      - ./docker/mysqldata:/var/lib/mysql
      - ./docker/dumps:/tmp/dump
    environment:
      - MYSQL_USER=webadm
      - MYSQL_PASSWORD=A123456
      - MYSQL_ROOT_PASSWORD=A123456
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306
